#!/bin/sh
# helper function for displaying text on acme
set -e

winid=$( 9p read acme/new/ctl | tr -s ' ' | cut -d ' ' -f 2 )
printf 'name %s\n' $1 | 9p write acme/$winid/ctl

while read -r line; do
	echo $line
done | 9p write acme/$winid/body

# make sure at least some text is displayed
printf clean | 9p write acme/$winid/ctl
printf '0,0' | 9p write acme/$winid/addr
printf 'dot=addr' | 9p write acme/$winid/ctl
printf show | 9p write acme/$winid/ctl
