#!/bin/sh
# a gemini client written for acme
# i would use rc but i'm more comfortable with standard bourne shell script

url=${1#gemini://}
url=${url%%/*}

# BUG: this client will only connect to port 1965.
#  should be fine for most servers, but it should be fixed somehow
port=1965

get() {
	echo "Hostname: $1"
	echo "Port: $2"
	openssl s_client -crlf -quiet \
	                 -no_ssl3 -no_tls1 -no_tls1_1 \
	                 -connect $1:$2 -servername $1
}

echo $1 | get $url $port | \
tr [:blank:] ' ' | 9 awk -F ' ' -v "hostname=$url" '
	function parse_url(url) {
		if (index(url, "/") == 1) {
			return "gemini://" hostname url
		} else if (index(url, "gemini://") == 0) {
			return "gemini://" hostname "/" url
		} else {
			return url
		}
	}

	/^=>/ {
		str = "=>"
		if ($1 == str) {
			$1 = ""
			url = parse_url($2)
			$2 = ""
		} else {
			sub(/=>/, "")
			url = parse_url($1)
			$1 = ""
		}

		printf("%s\n=>\t%s\n", $0, url)
		next
	}

	/^\* / {
		sub(/\*/, "•")
		print
		next
	}
	{ print($0) }
' | displayonacme $1
